POST http://localhost:3000/clients HTTP/1.1
content-type: application/json

{"name": "Alper", "age": 28}

###

GET http://localhost:3000/clients/67671f7d34b5790e23f618e9 HTTP/1.1

###

POST http://localhost:3000/clients/67696772cd255381bdebc8a0/reservations HTTP/1.1
content-type: application/json

{"managerId": "676b00c12a65bcdb4dd3cf6a"}

###

DELETE http://localhost:3000/clients/67671eeab66e01624d25f117 HTTP/1.1

###

PATCH http://localhost:3000/clients/676704801d12c38dc15d618e HTTP/1.1
content-type: application/json

{"name": "Hector Salamanca"}

###

POST http://localhost:3000/managers HTTP/1.1
content-type: application/json

{"name": "Gustavo Ping", "age": 54}

###

DELETE http://localhost:3000/managers/676ae3aa72b498e5f11b0a00 HTTP/1.1

###

GET http://localhost:3000/managers/676969298d681211d25a0a1b HTTP/1.1

###

POST http://localhost:3000/shelters HTTP/1.1
content-type: application/json

{
    "name": "ankaraMessi",
    "animalCapacity": 76,
    "contactInfo": "676b00882a65bcdb4dd3cf65",
    "animalList": [],
    "reservationList": []
}
###

POST http://localhost:3000/contact-infos HTTP/1.1
content-type: application/json

{
    "phone":"+335252352" , 
    "email":"mecit@shelter.com",
    "location":"Ankara"
}

###

POST http://localhost:3000/managers HTTP/1.1
content-type: application/json

{
    "name": "Mecit",
    "age": 45,
    "shelter": "676b00a22a65bcdb4dd3cf67"
}
###